void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _putchar(char c);
void do_print(char *s);
int _sqrt_recursion(int n);
int _pow_recursion(int x, int y);
int sq_root(int, int);
int is_prime_number(int n);
int is_prime(int, int);
int wildcmp(char *s1, char *s2);
int wildcmp(char *s1, char *s2);
int is_palindrome(char *s);
int is_palindrome_(char *s, char *start, char *end);
void lower(char *c);
int strleng(char *s);
int skip(char c);
