int _putchar(char c);
void *malloc_checked(unsigned int b);
char *string_nconcat(char *s1, char *s2, unsigned int n);
void *_calloc(unsigned int nmemb, unsigned int size);
char *copyof(char *s1, char *s2, unsigned int n);
unsigned int strlen_(char *string);
int *array_range(int min, int max);
void *_realloc(void *ptr, unsigned int old_size, unsigned int new_size);
int _putstring(char *str);
int writeline(char *str);
int isspace_(char c);
int atoi_(char *str);
int isdigit_(char x);
int isdigits(char *x);
void printint(int n);
unsigned int productof(unsigned int a, unsigned int b);
