#!/bin/bash

# Convinient for running our shell with minimal tying
# Ensure to inlcude the current path in the system PATH

clear

# compile 3-*.c -o calc && calc $*
# gcc c.c -o opcodes && opcodes $*

gcc 100-main_opcodes.c -o opcodes && opcodes $*